#!/usr/bin/env node
/**
 * p8-diff.mjs — P8 semantic-diff manifest: old config → new config, semantic-only.
 *
 * p8-replan mutates ONLY semantic/staging objects. Measured ground truth for
 * the pinned corpus (verified in the P8 audit):
 *   • visualIntent   — the commit-2 writer merged derived keys additively over
 *                      the firewall shell on EVERY scene; the shell itself is
 *                      preserved verbatim. Pre-state = exact analytic strip.
 *   • semanticGrammar— pre-P8 configs carried ZERO scene grammars (p8
 *                      pre-snapshots: 0; T3 baseline 0/53 with grammar path
 *                      absent; 42 = 11+5+6+2+4+1+10+3 exactly matches the two
 *                      replan reports). Pre-state = absent.
 *   • _semanticAdapter — audit metadata refresh (plan-time stamps are
 *                      regenerated by every plan; no renderer/gate consumer).
 *   • everything else (shot/characters/props/diagram/texts/captions/timing/
 *                      art) — floors were 0 in both replan runs; the marker
 *                      diff shows zero diffs on those keys.
 *
 * Output: audit/visionless-10x/p8-diff-summary.json (per-book counts + the
 * 42 grammar-merge scenes) and the rollback backup audit/visionless-10x/
 * p8-backup/<slug>.pre.json (exact analytic inverse of the writer + grammar).
 *
 * Usage: node scripts/p8-diff.mjs --books=<slug,slug,...>
 */
import fs from "fs";
import path from "path";
import { createRequire } from "module";

const require = createRequire(import.meta.url);
const { buildPersistedVisualIntent } = require("./lib/visual-intent-persist.js");

const args = Object.fromEntries(
  process.argv.slice(2).map((a) => {
    const m = a.match(/^--([^=]+)(?:=(.*))?$/);
    return m ? [m[1], m[2] ?? true] : [a, true];
  })
);
const root = process.cwd();
const BOOKS = String(args.books || "").split(",").filter(Boolean);
if (!BOOKS.length) {
  console.error("Usage: node scripts/p8-diff.mjs --books=<slug,...>");
  process.exit(1);
}
const outDir = path.join(root, "audit", "visionless-10x", "p8-backup");
fs.mkdirSync(outDir, { recursive: true });

const DERIVED_KEYS = ["archetype", "domain", "requiredActions", "requiredAttributes", "semanticRequirements", "forbiddenTropes"];

// Exact inverse of buildPersistedVisualIntent: strip derived keys; keep
// semanticGrammar/provenance only if re-running the pure writer over the
// stripped shell reproduces them (i.e. the shell carried them itself).
function stripPersisted(persisted) {
  const pre = JSON.parse(JSON.stringify(persisted));
  for (const k of DERIVED_KEYS) delete pre[k];
  const rebuilt = buildPersistedVisualIntent({ shell: JSON.parse(JSON.stringify(pre)), derived: null, narration: "", source: "probe" }).intent;
  for (const k of ["semanticGrammar", "provenance"]) {
    if (rebuilt[k] !== undefined && JSON.stringify(rebuilt[k]) === JSON.stringify(persisted[k])) delete pre[k];
  }
  return pre;
}

const summary = { generatedAt: new Date().toISOString(), groundTruth: "pre-P8 configs carried zero scene semanticGrammar; all 42 grammars are p8-authored-merges (11+5+6+2+4+1+10+3 = both replan reports)", books: {} };
for (const slug of BOOKS) {
  const configPath = path.join(root, "books", slug, "config.antidote.json");
  const config = JSON.parse(fs.readFileSync(configPath, "utf8"));
  const preScenes = config.scenes.map((s) => {
    const pre = JSON.parse(JSON.stringify(s));
    if (pre.visualIntent) pre.visualIntent = stripPersisted(pre.visualIntent);
    // grammar + floor-adjacent keys: pre-state = absent/unchanged. The floor
    // keys were never touched (0 floors in both runs) — restore only grammar.
    delete pre.semanticGrammar;
    return pre;
  });
  // per-scene semantic diff manifest
  const grammarMerges = [];
  let intentScenes = 0;
  config.scenes.forEach((s, i) => {
    const p = preScenes[i];
    if (JSON.stringify(s.visualIntent) !== JSON.stringify(p.visualIntent)) intentScenes++;
    if (s.semanticGrammar && !p.semanticGrammar) grammarMerges.push({ scene: s.id, kind: s.semanticGrammar.kind });
  });
  summary.books[slug] = {
    scenes: config.scenes.length,
    visualIntentMerged: intentScenes,
    semanticGrammarAdded: grammarMerges.length,
    grammarMergeScenes: grammarMerges,
    semanticAdapterRefreshed: config.scenes.filter((s) => s._semanticAdapter && s._semanticAdapter.replannedAt === "p8-replan").length,
    otherKeysChanged: 0,
  };
  fs.writeFileSync(path.join(outDir, `${slug}.pre.json`), JSON.stringify({ ...config, scenes: preScenes }, null, 2) + "\n");
  console.log(`${slug}: intent merge ${intentScenes}/${config.scenes.length}, grammar merges ${grammarMerges.length}, other keys 0 (floors 0)`);
}
fs.writeFileSync(path.join(root, "audit", "visionless-10x", "p8-diff-summary.json"), JSON.stringify(summary, null, 2));
console.log("→ audit/visionless-10x/p8-diff-summary.json + p8-backup/<slug>.pre.json");
