#!/usr/bin/env node
/**
 * thumbnail-critic.js — Scores 5 thumbnail concepts + image candidates,
 * selects the winner, and updates youtube-meta.json with the winning brief.
 *
 * Scoring is deterministic (no API). Each concept is scored on 10 criteria
 * weighted by CTR-relevance. The winner is the highest-scoring concept whose
 * image file actually exists (was successfully generated by gen-thumbnail.py).
 *
 * Usage:
 *   node scripts/thumbnail-critic.js --slug=the-republic
 *   node scripts/thumbnail-critic.js --slug=the-republic --dry-run
 *
 * Input:  books/<slug>/thumbnail-concepts.json
 *         books/<slug>/youtube-meta.json
 *         public/scenes/<slug>/thumbnail-concept-<angle>.png (existence check)
 *
 * Output: books/<slug>/thumbnail-concepts.json (winner flagged + scores)
 *         books/<slug>/youtube-meta.json (thumbnail brief updated to winner)
 */

"use strict";

const fs = require("fs");
const path = require("path");
const {
  CRITIC_WEIGHTS,
  LAYOUT_RULES,
  genericityScore,
  hookScore,
  layoutMatchScore,
} = require("./lib/thumbnail-concepts");

const ROOT = path.join(__dirname, "..");
const args = Object.fromEntries(
  process.argv.slice(2).map((a) => {
    const m = a.match(/^--([^=]+)=(.*)$/);
    return m ? [m[1], m[2]] : [a.replace(/^--/, ""), true];
  }),
);

const SLUG = args.slug;
const DRY_RUN = !!args["dry-run"];

if (!SLUG) {
  console.error("Usage: node scripts/thumbnail-critic.js --slug=<slug> [--dry-run]");
  process.exit(1);
}

// ── READ INPUTS ───────────────────────────────────────────────────────────────
const conceptsPath = path.join(ROOT, "books", SLUG, "thumbnail-concepts.json");
const metaPath = path.join(ROOT, "books", SLUG, "youtube-meta.json");

if (!fs.existsSync(conceptsPath)) {
  console.error(`❌ thumbnail-concepts.json not found. Run thumbnail-art-director.js first.`);
  process.exit(1);
}
if (!fs.existsSync(metaPath)) {
  console.error(`❌ youtube-meta.json not found.`);
  process.exit(1);
}

const conceptsDoc = JSON.parse(fs.readFileSync(conceptsPath, "utf8"));
const meta = JSON.parse(fs.readFileSync(metaPath, "utf8"));

const concepts = conceptsDoc.concepts || [];
const titles = meta.titles || [];
const existingHook = meta.thumbnail?.hook || "";

// ── SCORER ────────────────────────────────────────────────────────────────────
/**
 * Score a single concept. Returns a 0–100 total score + per-criterion breakdown.
 */
function scoreConcept(concept) {
  const scores = {};

  // 1. Book specificity — does the visual subject mention book-specific terms?
  //    Proxy: count proper nouns / named concepts in visualSubject
  const subj = concept.visualSubject || "";
  const properNouns = (subj.match(/\b[A-Z][a-z]{3,}\b/g) || []).length;
  const motifBonus = concept.iconicMotif ? 0.2 : 0;
  scores.bookSpecificity = Math.min(1, properNouns * 0.15 + motifBonus + (subj.length > 100 ? 0.2 : 0));

  // 2. Concept clarity — hook and visual angle tell the same story
  const angleKeywords = {
    power: ["rule", "control", "power", "city", "authority", "crowd", "philosopher", "king"],
    soul: ["soul", "mind", "control", "inner", "divided", "psychological", "tripart", "appetite"],
    scene: ["cave", "shadow", "fire", "city", "ship", "scene", "allegory", "light"],
    conflict: ["crowd", "beast", "tyrant", "democracy", "opposing", "force", "chaos"],
    mystery: ["symbolic", "abstract", "metaphor", "hidden", "truth", "mystery", "lies"],
  };
  const kws = angleKeywords[concept.angle] || [];
  const subjLower = subj.toLowerCase();
  const hookLower = (concept.hook || "").toLowerCase();
  const matchCount = kws.filter((k) => subjLower.includes(k) || hookLower.includes(k)).length;
  scores.conceptClarity = Math.min(1, matchCount / 3);

  // 3. Genericity penalty — penalize "generic dramatic man"
  scores.genericityPenalty = genericityScore(subj);

  // 4. Hook quality — length, originality, punch
  scores.hookLength = hookScore(concept.hook, titles);

  // 5. Layout match — is the layout the right one for this angle?
  scores.layoutMatch = layoutMatchScore(concept.angle, concept.layout);

  // 6. Palette contrast — does the concept use strong contrast descriptors?
  const lighting = (concept.lighting || "").toLowerCase();
  const highContrastTerms = ["rim", "chiaroscuro", "spotlight", "hard", "split", "dramatic", "contrast", "deep shadow"];
  const contrastCount = highContrastTerms.filter((t) => lighting.includes(t)).length;
  scores.paletteContrast = Math.min(1, contrastCount * 0.25);

  // 7. Negative space — is there clear left space for text?
  const layout = LAYOUT_RULES[concept.layout] || {};
  scores.negativeSpace =
    layout.textSide === "left" ? 1.0
    : concept.negativeSpace === "left" ? 0.8
    : 0.3;

  // 8. Title complement — hook should NOT repeat the title verbatim
  const titleWords = new Set(
    (meta.title || "").toLowerCase().split(/\s+/).filter((w) => w.length > 3),
  );
  const hookWords = (concept.hook || "").toLowerCase().split(/\s+/);
  const titleOverlap = hookWords.filter((w) => titleWords.has(w)).length / Math.max(hookWords.length, 1);
  scores.titleComplement = titleOverlap > 0.5 ? 0.1 : titleOverlap > 0.25 ? 0.5 : 1.0;

  // ── WEIGHTED TOTAL ──
  const total = Object.entries(CRITIC_WEIGHTS).reduce((sum, [key, weight]) => {
    return sum + (scores[key] || 0) * weight;
  }, 0);

  return { scores, total: Math.round(total * 100) };
}

// ── EXISTENCE CHECK ───────────────────────────────────────────────────────────
function imageExists(concept) {
  const abs = path.join(ROOT, "public", concept.imagePath);
  return fs.existsSync(abs);
}

// ── SCORE ALL CONCEPTS ────────────────────────────────────────────────────────
console.log(`\n🎬 Thumbnail Critic — ${conceptsDoc.title || SLUG}`);
console.log(`   Scoring ${concepts.length} concepts...\n`);

const scored = concepts.map((c) => {
  const result = scoreConcept(c);
  const imgExists = imageExists(c);
  // Heavy penalty if image doesn't exist (can't use a concept with no image)
  const effectiveScore = imgExists ? result.total : Math.round(result.total * 0.3);
  return { ...c, _score: result.total, _effectiveScore: effectiveScore, _imageExists: imgExists, _scoreBreakdown: result.scores };
});

// Sort by effective score
scored.sort((a, b) => b._effectiveScore - a._effectiveScore);

// Print scores
console.log("📊 Scores:");
for (const c of scored) {
  const img = c._imageExists ? "✓ img" : "✗ img";
  console.log(
    `   [${c.conceptId}] ${String(c._effectiveScore).padStart(3)}/100  ${c.hook.padEnd(28)} ${img}  layout:${c.layout}`,
  );
  // Print criterion breakdown
  for (const [k, w] of Object.entries(CRITIC_WEIGHTS)) {
    const s = c._scoreBreakdown[k] || 0;
    const contribution = Math.round(s * w * 100);
    console.log(
      `            ${k.padEnd(20)} ${String(Math.round(s * 100)).padStart(3)}%  × ${String(Math.round(w * 100)).padStart(2)}w = ${String(contribution).padStart(2)}pts`,
    );
  }
}

// Select winner (highest effective score)
const winner = scored[0];
winner._winner = true;

console.log(`\n🏆 WINNER: [${winner.conceptId}] "${winner.hook}" (score: ${winner._effectiveScore}/100)`);
if (!winner._imageExists) {
  console.warn(`   ⚠ Warning: winner image not found at public/${winner.imagePath}`);
  console.warn(`     Run gen-thumbnail.py --concepts first, or winner will use fallback.`);
}

// ── UPDATE CONCEPTS JSON ──────────────────────────────────────────────────────
const updatedConcepts = scored.map((c) => ({
  ...c,
  _needsCriticScore: false,
}));

const updatedDoc = {
  ...conceptsDoc,
  concepts: updatedConcepts,
  winner: {
    conceptId: winner.conceptId,
    angle: winner.angle,
    hook: winner.hook,
    layout: winner.layout,
    imagePath: winner.imagePath,
    cutPath: winner.cutPath,
    score: winner._effectiveScore,
    scoredAt: new Date().toISOString(),
  },
};

// ── UPDATE YOUTUBE-META.JSON THUMBNAIL BRIEF ──────────────────────────────────
// This is the key output: the winner concept becomes the canonical thumbnail brief
// that gen-thumbnail.py and the Remotion Thumb- composition both read.
const updatedMeta = {
  ...meta,
  thumbnail: {
    ...meta.thumbnail,
    hook: winner.hook,
    subject: winner.visualSubject,
    layout: winner.layout,
    image: winner.imagePath,
    cut: winner._imageExists ? winner.cutPath : meta.thumbnail?.cut,
    concept: winner.conceptId,
    angle: winner.angle,
    fluxPrompt: winner.fluxPrompt,
    criticScore: winner._effectiveScore,
    _artDirected: true,
  },
};

if (DRY_RUN) {
  console.log("\n[dry-run] Would update:", conceptsPath);
  console.log("[dry-run] Would update:", metaPath);
  console.log("\nUpdated thumbnail brief:");
  console.log(JSON.stringify(updatedMeta.thumbnail, null, 2));
} else {
  fs.writeFileSync(conceptsPath, JSON.stringify(updatedDoc, null, 2));
  fs.writeFileSync(metaPath, JSON.stringify(updatedMeta, null, 2));
  console.log(`\n✅ Updated: ${conceptsPath}`);
  console.log(`✅ Updated: ${metaPath}`);
  console.log(`\n   thumbnail.hook    → "${winner.hook}"`);
  console.log(`   thumbnail.layout  → "${winner.layout}"`);
  console.log(`   thumbnail.image   → "${winner.imagePath}"`);
  console.log(`\n   Re-render thumbnail: npx remotion still Thumb-${SLUG} out/thumbnail-${SLUG}.png --frame=0`);
}
