// AUTO-GENERATED by scripts/gen-books-registry.js — do not edit by hand.
// Regenerate with: node scripts/gen-books-registry.js

import ant_the_hunger_games from '../books/the-hunger-games/config.antidote.json';
import ant_meta_the_hunger_games from '../books/the-hunger-games/youtube-meta.json';
import ant_the_republic from '../books/the-republic/config.antidote.json';
import ant_meta_the_republic from '../books/the-republic/youtube-meta.json';

export type Palette = { paper: string; ink: string; red: string; gold: string; captionHighlight?: string };

export type BookEntry = {
  slug: string;
  engine: 'vox' | 'antidote';
  config: any;
  meta: any | null;
};

export type AntidoteBookEntry = {
  slug: string;
  engine: 'vox' | 'antidote';
  config: any;
  meta?: any | null;
};

// Per-book palettes (from books/<slug>/book.json). resolvePalette() in voxkit and
// the Antidote thumbnail read this so each book has its own color identity.
export const BOOK_PALETTES: Record<string, Palette> = {
  'the-hunger-games': { paper: '#F9F6F0', ink: '#18181B', red: '#C2410C', gold: '#D97706' },
  'the-republic': { paper: '#F6F1E8', ink: '#181514', red: '#B83A24', gold: '#C98A2C' },
};

// Books opted into the palette-tinted background (new books; see book.json.bgTint).
export const BOOK_BG_TINT: Record<string, boolean> = {
  'the-hunger-games': true,
  'the-republic': true,
};

export const BOOKS: BookEntry[] = [

];

export const ANTIDOTE_BOOKS: AntidoteBookEntry[] = [
  {
    slug: 'the-hunger-games',
    engine: 'antidote',
    config: ant_the_hunger_games as any,
    meta: ant_meta_the_hunger_games as any,
  },
  {
    slug: 'the-republic',
    engine: 'antidote',
    config: ant_the_republic as any,
    meta: ant_meta_the_republic as any,
  },
];
