// AUTO-GENERATED by scripts/gen-books-registry.js — do not edit by hand.
// Regenerate with: node scripts/gen-books-registry.js
import cfg_all_the_light_we_cannot_see from '../books/all-the-light-we-cannot-see/config.vox.json';
import meta_all_the_light_we_cannot_see from '../books/all-the-light-we-cannot-see/youtube-meta.json';
import cfg_dust from '../books/dust/config.vox.json';
import meta_dust from '../books/dust/youtube-meta.json';
import cfg_east_of_eden from '../books/east-of-eden/config.vox.json';
import meta_east_of_eden from '../books/east-of-eden/youtube-meta.json';
import cfg_frederick_douglass_prophet_of_freedom from '../books/frederick-douglass-prophet-of-freedom/config.vox.json';
import meta_frederick_douglass_prophet_of_freedom from '../books/frederick-douglass-prophet-of-freedom/youtube-meta.json';
import cfg_psychology_of_money from '../books/psychology-of-money/config.vox.json';
import meta_psychology_of_money from '../books/psychology-of-money/youtube-meta.json';
import cfg_sapiens from '../books/sapiens/config.vox.json';
import meta_sapiens from '../books/sapiens/youtube-meta.json';
import cfg_shift from '../books/shift/config.vox.json';
import meta_shift from '../books/shift/youtube-meta.json';
import cfg_single_dad_dilemma from '../books/single-dad-dilemma/config.vox.json';
import meta_single_dad_dilemma from '../books/single-dad-dilemma/youtube-meta.json';
import cfg_slow_productivity from '../books/slow-productivity/config.vox.json';
import meta_slow_productivity from '../books/slow-productivity/youtube-meta.json';
import cfg_the_frozen_river from '../books/the-frozen-river/config.vox.json';
import meta_the_frozen_river from '../books/the-frozen-river/youtube-meta.json';
import cfg_the_stranger from '../books/the-stranger/config.vox.json';
import meta_the_stranger from '../books/the-stranger/youtube-meta.json';
import ant_a_good_man_is_hard_to_find from '../books/a-good-man-is-hard-to-find/config.antidote.json';
import ant_meta_a_good_man_is_hard_to_find from '../books/a-good-man-is-hard-to-find/youtube-meta.json';
import ant_clear_thinking from '../books/clear-thinking/config.antidote.json';
import ant_meta_clear_thinking from '../books/clear-thinking/youtube-meta.json';
import ant_crime_and_punishment from '../books/crime-and-punishment/config.antidote.json';
import ant_meta_crime_and_punishment from '../books/crime-and-punishment/youtube-meta.json';
import ant_death_row from '../books/death-row/config.antidote.json';
import ant_die_with_zero from '../books/die-with-zero/config.antidote.json';
import ant_meta_die_with_zero from '../books/die-with-zero/youtube-meta.json';
import ant_fahrenheit_451 from '../books/fahrenheit-451/config.antidote.json';
import ant_meta_fahrenheit_451 from '../books/fahrenheit-451/youtube-meta.json';
import ant_feel_good_productivity from '../books/feel-good-productivity/config.antidote.json';
import ant_meta_feel_good_productivity from '../books/feel-good-productivity/youtube-meta.json';
import ant_lolita from '../books/lolita/config.antidote.json';
import ant_meta_lolita from '../books/lolita/youtube-meta.json';
import ant_million_dollar_weekend from '../books/million-dollar-weekend/config.antidote.json';
import ant_meta_million_dollar_weekend from '../books/million-dollar-weekend/youtube-meta.json';
import ant_psychology_of_money from '../books/psychology-of-money/config.antidote.json';
import ant_meta_psychology_of_money from '../books/psychology-of-money/youtube-meta.json';
import ant_stolen_focus from '../books/stolen-focus/config.antidote.json';
import ant_meta_stolen_focus from '../books/stolen-focus/youtube-meta.json';
import ant_surrounded_by_idiots from '../books/surrounded-by-idiots/config.antidote.json';
import ant_meta_surrounded_by_idiots from '../books/surrounded-by-idiots/youtube-meta.json';
import ant_the_courage_to_be_disliked from '../books/the-courage-to-be-disliked/config.antidote.json';
import ant_meta_the_courage_to_be_disliked from '../books/the-courage-to-be-disliked/youtube-meta.json';
import ant_the_myth_of_sisyphus from '../books/the-myth-of-sisyphus/config.antidote.json';
import ant_meta_the_myth_of_sisyphus from '../books/the-myth-of-sisyphus/youtube-meta.json';
import ant_the_republic from '../books/the-republic/config.antidote.json';
import ant_meta_the_republic from '../books/the-republic/youtube-meta.json';
import ant_the_southern_book_club_s_guide_to_slaying_vampires from '../books/the-southern-book-club-s-guide-to-slaying-vampires/config.antidote.json';
import ant_meta_the_southern_book_club_s_guide_to_slaying_vampires from '../books/the-southern-book-club-s-guide-to-slaying-vampires/youtube-meta.json';
import ant_unhinged from '../books/unhinged/config.antidote.json';
import ant_meta_unhinged from '../books/unhinged/youtube-meta.json';
import ant_we_were_liars from '../books/we-were-liars/config.antidote.json';
import ant_meta_we_were_liars from '../books/we-were-liars/youtube-meta.json';
import ant_we_were_liars_pilot from '../books/we-were-liars-pilot/config.antidote.json';

export type Palette = { paper: string; ink: string; red: string; gold: string; captionHighlight?: string };

export type BookEntry = {
  slug: string;
  engine: 'vox' | 'antidote';
  config: any;
  meta: any | null;
};

export type AntidoteBookEntry = {
  slug: string;
  engine: 'vox' | 'antidote';
  config: any;
  meta?: any | null;
};

// Per-book palettes (from books/<slug>/book.json). resolvePalette() in voxkit and
// the Antidote thumbnail read this so each book has its own color identity.
export const BOOK_PALETTES: Record<string, Palette> = {
  'clear-thinking': { paper: '#EDF1F3', ink: '#17242B', red: '#1C7C8C', gold: '#E4A93A' },
  'crime-and-punishment': { paper: '#F5F2EB', ink: '#181716', red: '#991B1B', gold: '#C28E38' },
  'death-row': { paper: '#F5F5F0', ink: '#1E232A', red: '#B91C1C', gold: '#D97706' },
  'dust': { paper: '#EAEFF4', ink: '#0D131F', red: '#DC2626', gold: '#EAB308' },
  'east-of-eden': { paper: '#F4EBDA', ink: '#1C1712', red: '#9C2B1B', gold: '#C99A3B' },
  'fahrenheit-451': { paper: '#F5F2EB', ink: '#171514', red: '#C2410C', gold: '#D97706' },
  'feel-good-productivity': { paper: '#FAF8F2', ink: '#181A20', red: '#E85D04', gold: '#F59E0B' },
  'million-dollar-weekend': { paper: '#FAF9F5', ink: '#111827', red: '#16A34A', gold: '#EAB308' },
  'psychology-of-money': { paper: '#DEE4DC', ink: '#17201A', red: '#2F8F5B', gold: '#D9A93A' },
  'shift': { paper: '#EAEFF5', ink: '#0F172A', red: '#C53030', gold: '#D97706' },
  'single-dad-dilemma': { paper: '#F1E4E1', ink: '#2A1D22', red: '#D64A6B', gold: '#E0A25C' },
  'slow-productivity': { paper: '#E6E5DE', ink: '#1C1E22', red: '#3E7CA8', gold: '#C99A48' },
  'stolen-focus': { paper: '#F6F5EF', ink: '#14161A', red: '#B91C1C', gold: '#D97706' },
  'the-myth-of-sisyphus': { paper: '#FBF9F5', ink: '#1C1917', red: '#DC2626', gold: '#D97706' },
  'the-republic': { paper: '#F6F1E8', ink: '#181514', red: '#B83A24', gold: '#C98A2C' },
  'the-southern-book-club-s-guide-to-slaying-vampires': { paper: '#FAF7F2', ink: '#1A1412', red: '#8B1A1A', gold: '#C4973B' },
  'we-were-liars': { paper: '#F8F8F4', ink: '#0F172A', red: '#DC2626', gold: '#D97706' },
  'we-were-liars-pilot': { paper: '#F8F8F4', ink: '#0F172A', red: '#DC2626', gold: '#D97706' },
};

// Books opted into the palette-tinted background (new books; see book.json.bgTint).
export const BOOK_BG_TINT: Record<string, boolean> = {
  'a-good-man-is-hard-to-find': true,
  'all-the-light-we-cannot-see': true,
  'crime-and-punishment': true,
  'death-row': true,
  'die-with-zero': true,
  'dust': true,
  'fahrenheit-451': true,
  'feel-good-productivity': true,
  'frederick-douglass-prophet-of-freedom': true,
  'lolita': true,
  'million-dollar-weekend': true,
  'sapiens': true,
  'shift': true,
  'stolen-focus': true,
  'surrounded-by-idiots': true,
  'the-courage-to-be-disliked': true,
  'the-myth-of-sisyphus': true,
  'the-republic': true,
  'the-southern-book-club-s-guide-to-slaying-vampires': true,
  'the-stranger': true,
  'unhinged': true,
  'we-were-liars': true,
  'we-were-liars-pilot': true,
};

export const BOOKS: BookEntry[] = [
  {
    slug: 'all-the-light-we-cannot-see',
    engine: 'vox',
    config: cfg_all_the_light_we_cannot_see as any,
    meta: meta_all_the_light_we_cannot_see as any,
  },
  {
    slug: 'dust',
    engine: 'vox',
    config: cfg_dust as any,
    meta: meta_dust as any,
  },
  {
    slug: 'east-of-eden',
    engine: 'vox',
    config: cfg_east_of_eden as any,
    meta: meta_east_of_eden as any,
  },
  {
    slug: 'frederick-douglass-prophet-of-freedom',
    engine: 'vox',
    config: cfg_frederick_douglass_prophet_of_freedom as any,
    meta: meta_frederick_douglass_prophet_of_freedom as any,
  },
  {
    slug: 'psychology-of-money',
    engine: 'vox',
    config: cfg_psychology_of_money as any,
    meta: meta_psychology_of_money as any,
  },
  {
    slug: 'sapiens',
    engine: 'vox',
    config: cfg_sapiens as any,
    meta: meta_sapiens as any,
  },
  {
    slug: 'shift',
    engine: 'vox',
    config: cfg_shift as any,
    meta: meta_shift as any,
  },
  {
    slug: 'single-dad-dilemma',
    engine: 'vox',
    config: cfg_single_dad_dilemma as any,
    meta: meta_single_dad_dilemma as any,
  },
  {
    slug: 'slow-productivity',
    engine: 'vox',
    config: cfg_slow_productivity as any,
    meta: meta_slow_productivity as any,
  },
  {
    slug: 'the-frozen-river',
    engine: 'vox',
    config: cfg_the_frozen_river as any,
    meta: meta_the_frozen_river as any,
  },
  {
    slug: 'the-stranger',
    engine: 'vox',
    config: cfg_the_stranger as any,
    meta: meta_the_stranger as any,
  },
];

export const ANTIDOTE_BOOKS: AntidoteBookEntry[] = [
  {
    slug: 'a-good-man-is-hard-to-find',
    engine: 'antidote',
    config: ant_a_good_man_is_hard_to_find as any,
    meta: ant_meta_a_good_man_is_hard_to_find as any,
  },
  {
    slug: 'clear-thinking',
    engine: 'antidote',
    config: ant_clear_thinking as any,
    meta: ant_meta_clear_thinking as any,
  },
  {
    slug: 'crime-and-punishment',
    engine: 'antidote',
    config: ant_crime_and_punishment as any,
    meta: ant_meta_crime_and_punishment as any,
  },
  {
    slug: 'death-row',
    engine: 'antidote',
    config: ant_death_row as any,
    meta: null,
  },
  {
    slug: 'die-with-zero',
    engine: 'antidote',
    config: ant_die_with_zero as any,
    meta: ant_meta_die_with_zero as any,
  },
  {
    slug: 'fahrenheit-451',
    engine: 'antidote',
    config: ant_fahrenheit_451 as any,
    meta: ant_meta_fahrenheit_451 as any,
  },
  {
    slug: 'feel-good-productivity',
    engine: 'antidote',
    config: ant_feel_good_productivity as any,
    meta: ant_meta_feel_good_productivity as any,
  },
  {
    slug: 'lolita',
    engine: 'antidote',
    config: ant_lolita as any,
    meta: ant_meta_lolita as any,
  },
  {
    slug: 'million-dollar-weekend',
    engine: 'antidote',
    config: ant_million_dollar_weekend as any,
    meta: ant_meta_million_dollar_weekend as any,
  },
  {
    slug: 'psychology-of-money',
    engine: 'vox',
    config: ant_psychology_of_money as any,
    meta: ant_meta_psychology_of_money as any,
  },
  {
    slug: 'stolen-focus',
    engine: 'antidote',
    config: ant_stolen_focus as any,
    meta: ant_meta_stolen_focus as any,
  },
  {
    slug: 'surrounded-by-idiots',
    engine: 'antidote',
    config: ant_surrounded_by_idiots as any,
    meta: ant_meta_surrounded_by_idiots as any,
  },
  {
    slug: 'the-courage-to-be-disliked',
    engine: 'antidote',
    config: ant_the_courage_to_be_disliked as any,
    meta: ant_meta_the_courage_to_be_disliked as any,
  },
  {
    slug: 'the-myth-of-sisyphus',
    engine: 'antidote',
    config: ant_the_myth_of_sisyphus as any,
    meta: ant_meta_the_myth_of_sisyphus as any,
  },
  {
    slug: 'the-republic',
    engine: 'antidote',
    config: ant_the_republic as any,
    meta: ant_meta_the_republic as any,
  },
  {
    slug: 'the-southern-book-club-s-guide-to-slaying-vampires',
    engine: 'antidote',
    config: ant_the_southern_book_club_s_guide_to_slaying_vampires as any,
    meta: ant_meta_the_southern_book_club_s_guide_to_slaying_vampires as any,
  },
  {
    slug: 'unhinged',
    engine: 'antidote',
    config: ant_unhinged as any,
    meta: ant_meta_unhinged as any,
  },
  {
    slug: 'we-were-liars',
    engine: 'antidote',
    config: ant_we_were_liars as any,
    meta: ant_meta_we_were_liars as any,
  },
  {
    slug: 'we-were-liars-pilot',
    engine: 'antidote',
    config: ant_we_were_liars_pilot as any,
    meta: null,
  },
];
